name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: ls /home/runner/work/laravel-bus/laravel-bus/ && composer install --prefer-dist --no-progress
    - name: Test
      run: vendor/bin/phpunit